### PR TITLE
Added PasswordGenerator in Python

### PR DESCRIPTION
**Pull request by haris-bit**
Please accept this pull request for the hacktoberfest 2022

### CODE REVIEW

**Comment by sid-am-ahd935** [comment]
You are halfway there @haris-bit. Our guidelines specify any Python contribution must be of more than 40 lines. You can try to add GUI in this program using tkinter or making it a CLI program using Argparse to make it eligible for submission.

**Comment by haris-bit** [comment]
ok, got it.

**Comment by sid-am-ahd935** [comment]
Any updates @haris-bit ?

**Comment by haris-bit** [comment]
I wrote the code with tkinter but the lines aren't more than what's
required.

**Comment by haris-bit** [comment]
It's only 30 lines of code

**Comment by sid-am-ahd935** [comment]
Hi @haris-bit, just add your tkinter part of the code inside a function called "main" and then add:

- if __name__ == "__main__":
-     main()

And try to add something else, even suitable comments in the code is also appreciable.
You are close to done.

**Comment by haris-bit** [comment]
ok, thanks will update in a couple of hours.

**Comment by haris-bit** [comment]
I'm creating a new pull request for updated version.

**Comment by haris-bit** [comment]
Thanks for helping me out, man. I really appreciate it 🙂

**Comment by haris-bit** [comment]
I might have to close this pull request in order to create a new one.

**Pull request closed without merging**
