### PR TITLE
Added Hangman game using Python

### PR DESCRIPTION
**Pull request by vilasrhegde**

### CODE REVIEW

**Comment by sid-am-ahd935** [comment]
First create an issue then create a pull request @vilasrhegde

**Comment by sid-am-ahd935** [comment]
@vilasrhegde Create a folder of your file name, add your program to the folder. Copy all your dictionary words into a single dictionary.txt file and use the text file for your operations

**Comment by vilasrhegde** [comment]
@sid-am-ahd935 would you check my PR?

**Comment by sid-am-ahd935** [comment]
@vilasrhegde Your commits are acceptable

**Comment by vilasrhegde** [comment]
@sid-am-ahd935 thanks

**Pull request merged**
