### PR TITLE
Create Puzzle_game.java

### PR DESCRIPTION
**Pull request by vibhoooo**
I have made a puzzle game in java using AWT. please review my Pr and merge it as soon as possible.
Thank You

### CODE REVIEW

**Comment by sid-am-ahd935** [comment]
Is this a unique PR on your behalf?

**Comment by vibhoooo** [comment]
yes

**Comment by vibhoooo** [comment]
do merge it if you find it useful.It is a puzzle game in java.

**Comment by sid-am-ahd935** [comment]
Create an issue regarding this pr

**Comment by vibhoooo** [comment]
i think it was already created

**Comment by vibhoooo** [comment]
It is a good first issue Create A Fun Java Code Snippet
<https://github.com/sid-am-ahd935/Aliahns/issues/3>

**Comment by sid-am-ahd935** [comment]
Comment there to get yourself assigned

**Comment by sid-am-ahd935** [comment]
Add a folder in Java with the same name as the file name. Add this file into this folder and add a README.md in this new folder. Add some screenshots and possible brief explanation  of its workings

**Comment by vibhoooo** [comment]
ok

**Comment by sid-am-ahd935** [comment]
Any updates @vibhoooo ?

**Comment by vibhoooo** [comment]
yes sir I am doing it.

**Comment by vibhoooo** [comment]
Done

**Pull request closed without merging**
