### PR TITLE
Added Tic Tac Toe game in Python

### PR DESCRIPTION
**Pull request by Rahul-Jain-1**
Please merge this pull request.

### CODE REVIEW

**Comment by sid-am-ahd935** [comment]
Hi @Rahul-Jain-1, but this issue is already resolved. Please create a new issue and work on that one.

**Comment by Rahul-Jain-1** [comment]
I have done it before NNrepos.

**Comment by sid-am-ahd935** [comment]
But the issue was already taken up by @NNRepos . Do not worry you can create a new issue for a different program, or in different language if available.

**Comment by Rahul-Jain-1** [comment]
ok thanks @sid-am-ahd935 I will add new project .

**Pull request closed without merging**
