### PR TITLE
random password generator in java

### PR DESCRIPTION
**Pull request by FaiyazUllah786**

### CODE REVIEW

**Comment by sid-am-ahd935** [comment]
Hi @FaiyazUllah786, for java minimum source code size is of 70 lines. Please add some more features to your code base.

**Comment by sid-am-ahd935** [comment]
Hi @FaiyazUllah786, please increase your code base size to about 70 lines.

**Comment by FaiyazUllah786** [comment]
I don't think i'm able extend this program because it is not too vast..can
I add another issue regarding sudoku solver in Java..other than that?

**Comment by sid-am-ahd935** [comment]
Hi @FaiyazUllah786, you can definitely work on the new issue. I will close this PR as invalid (not capable for merging). 
All the best for your next contribution.

**Pull request closed without merging**
