### PR TITLE
Updated python folder by adding pyramid pattern

### PR DESCRIPTION
**Pull request by JoydeepMallick**

### CODE REVIEW

**Review by sid-am-ahd935 — CHANGES_REQUESTED** [review]
Hi @JoydeepMallick, can you add some extra functionality in your program to make it larger than 40 lines. You may add suitable comments and use some functions to extend the program.

Our contribution guidelines require Python code to be greater than 40 lines.

**Comment by JoydeepMallick** [comment]
Sure, am working on it.

**Comment by JoydeepMallick** [comment]
I have made PR of the same.
Screenshot (419)

**Review by sid-am-ahd935 — APPROVED** [review]

**Comment by sid-am-ahd935** [comment]
Hi @JoydeepMallick amazing work, I am merging your commits, congratulations!!

**Pull request merged**
